Port = 1965
Hostname = "gemini.h14h.com"
CertPath = "/app/cert.pem"
KeyPath = "/app/key.pem"
DocBase = "/app/content/"
HomeDocBase = ""
GeminiExt = "gmi"
DefaultLang = "en"
AccessLog = "/dev/stdout"
ErrorLog = "/dev/stderr"
